import { Toaster } from '@/components/ui/sonner';
import { TRPCReactProvider } from '@/integrations/trpc/client';
import { Provider } from 'jotai';
import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import './globals.css';

const notoSans = Noto_Sans({
  variable: '--font-noto-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSans.variable} antialiased`}>
        <TRPCReactProvider>
          <NuqsAdapter>
            <Provider>
              <Toaster />
              {children}
            </Provider>
          </NuqsAdapter>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
